name: commit ci
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Lint
        run: swiftlint

      - name: Configure build environment
        run: |
          echo git_ref_name="$(git describe --always)" >> $GITHUB_ENV

      - name: Build Squirrel
        run: ./action-build.sh package

      - name: Install periphery
        run: brew install peripheryapp/periphery/periphery

      - name: Check Unused Code
        run: periphery scan --skip-build --index-store-path build/Index.noindex/DataStore

      - name: Upload Squirrel artifact
        uses: actions/upload-artifact@v4
        with:
          name: Squirrel-${{ env.git_ref_name }}.zip
          path: package/*.pkg
          # keep 90 days
          retention-days: 90
